# 使用精简的官方 Node.js 镜像作为构建阶段
FROM node:22-alpine AS build

# 设置工作目录
WORKDIR /app

# 复制 package.json 并安装依赖
COPY package.json package-lock.json* ./
RUN npm install --production

# 复制应用程序代码并构建
COPY . .
RUN npm run build

# 使用 Nginx 镜像作为生产环境阶段
FROM nginx:alpine

# 复制构建的静态文件到 Nginx 的静态文件目录
COPY --from=build /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]