version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - all

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "80"
    command: npm run serve
    networks:
      - all

  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - all

networks:
  all:
    driver: bridge
