# 使用官方的Python基础镜像
FROM python:3.9-slim

# 设置环境变量以确保 Python 在容器中能正确运行
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# 设置工作目录
WORKDIR /app

# 复制当前目录内容到工作目录
COPY . /app


# 安装依赖
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade --no-cache-dir pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用程序代码到工作目录
COPY . /app

# 设置默认命令
CMD gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app